name: Publish

on: [push, pull_request]

jobs:
  publish:
    name: Upload to pypi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    environment:
      name: release
      url: https://pypi.org/p/injectulate
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Pypa build
        run: |
          python3 -m pip install build --user
      - name: Build
        run: |
          python3 -m build --sdist --wheel --outdir dist
      - name: publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
