name: Publish

on: [push, pull_request]

jobs:
  publish:
    name: Upload to pypi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    environment:
      name: release
      url: https://pypi.org/p/injectulate
    permissions:
      id-token: write
    steps:
      - name: publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
